server:
  port: 8000

feign:
  hystrix:
    enabled: true

# 数据源配置
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: cloud-authentication-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://192.168.1.101:3306/sc_auth?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: 111111
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.101:8848

  #jwt的密钥
  security:
    oauth2:
      jwt:
        signingKey: 123456

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.example: debug
    org.springframework: warn
