server:
  port: 9527

feign:
  hystrix:
    enabled: true

#网关白名单，无需要签权url
gate:
  ignore:
    authentication:
      startWith: /oauth,/open,/v2/api-docs

spring:
  application:
    name: cloud-gateway
  security:
    oauth2:
      jwt:
        signingKey: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.101:8848
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: cloud-authentication-server      #路由的ID
          uri: lb://cloud-authentication-server:8000  #匹配后提供服务的路由地址
          predicates:                          # 断言，路径相匹配的进行路由
            - Path=/cloud-authentication-server/**
          filters:
            - StripPrefix=1

        - id: cloud-sysadmin
          uri: lb://cloud-sysadmin:8010
          predicates:
            - Path=/cloud-sysadmin/**
          filters:
            - StripPrefix=1

logging:
  level:
    com.everyman.springcloud.gateway.AuthProvider: info